/**
 * =============================================================================
 *  servo.c — Servo Motor Driver for TD-8120MG
 *  Board: WHEELTEC STM32F407VET6 (Rev 23.0)
 * =============================================================================
 */

#include "servo.h"

/* ===========================================================================
 *  Extern handle — generated by CubeMX, declared in main.c
 * =========================================================================== */
extern TIM_HandleTypeDef htim8;


/* ===========================================================================
 *  Initialisation
 * =========================================================================== */

void Servo_Init(void)
{
    HAL_TIM_PWM_Start(&htim8, TIM_CHANNEL_1);
    __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_1, SERVO_TICK_CENTER);
}


/* ===========================================================================
 *  Set position by raw tick value
 * =========================================================================== */

void Servo_SetTick(uint16_t tick)
{
    if (tick < SERVO_TICK_MIN) tick = SERVO_TICK_MIN;
    if (tick > SERVO_TICK_MAX) tick = SERVO_TICK_MAX;
    __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_1, tick);
}


/* ===========================================================================
 *  Set position by angle (0–180 degrees)
 * =========================================================================== */

void Servo_SetAngle(float angle)
{
    if (angle < 0.0f)   angle = 0.0f;
    if (angle > 180.0f) angle = 180.0f;

    /* Map 0–180 degrees to 25–125 ticks */
    uint16_t tick = (uint16_t)(SERVO_TICK_MIN +
                    (angle / 180.0f) * (SERVO_TICK_MAX - SERVO_TICK_MIN));

    __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_1, tick);
}


/* ===========================================================================
 *  Set steering position (-1.0 to +1.0)
 * =========================================================================== */

void Servo_SetSteering(float steer)
{
    if (steer < -1.0f) steer = -1.0f;
    if (steer > 1.0f)  steer = 1.0f;

    /*
     * Map -1.0 .. +1.0 to the practical steering range.
     * Centre = tick 75, range = 65 to 85
     * So half-range = 10 ticks in each direction.
     */
    float half_range = (float)(SERVO_STEER_MAX - SERVO_STEER_MIN) / 2.0f;
    float center     = (float)(SERVO_STEER_MAX + SERVO_STEER_MIN) / 2.0f;

    uint16_t tick = (uint16_t)(center + steer * half_range);

    __HAL_TIM_SET_COMPARE(&htim8, TIM_CHANNEL_1, tick);
}


/* ===========================================================================
 *  Get current tick value
 * =========================================================================== */

uint16_t Servo_GetTick(void)
{
    return (uint16_t)__HAL_TIM_GET_COMPARE(&htim8, TIM_CHANNEL_1);
}