/**
 * =============================================================================
 *  Motor Control with Encoder Feedback & RPM Calculation
 *  Board: WHEELTEC STM32F407VET6 (Rev 23.0)
 *  IDE:   STM32CubeIDE
 * =============================================================================
 *
 *  Pin Mapping (from schematic):
 *  -----------------------------------------------------------------------
 *  Motor A  | Driver U8  (AT8236) | IN1=PB8  (TIM4_CH3)  | IN2=PB9  (TIM4_CH4)
 *           | Encoder             | CH_A=PA15 (TIM2_CH1) | CH_B=PB3 (TIM2_CH2)
 *  -----------------------------------------------------------------------
 *  Motor B  | Driver U9  (AT8236) | IN1=PE5  (TIM9_CH1)  | IN2=PE6  (TIM9_CH2)
 *           | Encoder             | CH_A=PB4 (TIM3_CH1)  | CH_B=PB5 (TIM3_CH2)
 *  -----------------------------------------------------------------------
 *  Motor C  | Driver U10 (AT8236) | IN1=PE11 (TIM1_CH2)  | IN2=PE9  (TIM1_CH1)
 *           | Encoder             | CH_A=PB6 (TIM4_CH1)  | CH_B=PB7 (TIM4_CH2)
 *  -----------------------------------------------------------------------
 *  Motor D  | Driver U12 (AT8236) | IN1=PE14 (TIM1_CH4)  | IN2=PE13 (TIM1_CH3)
 *           | Encoder             | CH_A=PA0 (TIM5_CH1)  | CH_B=PA1 (TIM5_CH2)
 *  -----------------------------------------------------------------------
 *
 *  NOTE: Motor C encoder shares TIM4 with Motor A PWM. See the note in the
 *        header file about timer conflicts if you need all 4 motors at once.
 *
 *  ENCODER PARAMETERS (adjust to your motor):
 *    - ENCODER_PPR: Pulses Per Revolution of the encoder disc
 *    - GEAR_RATIO:  Motor gearbox ratio (e.g., 30:1)
 *    - The STM32 encoder mode counts on both edges of both channels (4x mode),
 *      so effective counts per output shaft revolution = PPR * 4 * GEAR_RATIO
 *
 *  HOW IT WORKS:
 *    1. TIM2 and TIM3 are configured in Encoder Mode to track Motor A & B
 *       position automatically in hardware.
 *    2. TIM6 generates a periodic interrupt (e.g., every 10 ms) to sample
 *       the encoder counters.
 *    3. In the TIM6 ISR callback, we compute the difference in counts (delta),
 *       then convert to RPM using:
 *         RPM = (delta / counts_per_rev) * (60 / sample_period_seconds)
 *
 * =============================================================================
 */

#include "motor_encoder.h"

/* ---------------------------------------------------------------------------
 *  Private variables
 * --------------------------------------------------------------------------- */

/* Last encoder counter values (for computing delta) */
static int32_t last_count_a = 0;
static int32_t last_count_b = 0;

/* Computed RPM values (updated in timer ISR) */
static volatile float rpm_motor_a = 0.0f;
static volatile float rpm_motor_b = 0.0f;

/* Raw encoder delta (signed, for direction info) */
static volatile int32_t encoder_delta_a = 0;
static volatile int32_t encoder_delta_b = 0;

/* ---------------------------------------------------------------------------
 *  Extern handles — generated by CubeMX, declared in main.c
 * --------------------------------------------------------------------------- */
extern TIM_HandleTypeDef htim2;   /* Motor A encoder        */
extern TIM_HandleTypeDef htim3;   /* Motor B encoder        */
extern TIM_HandleTypeDef htim4;   /* Motor A PWM            */
extern TIM_HandleTypeDef htim9;   /* Motor B PWM            */
extern TIM_HandleTypeDef htim6;   /* Sampling timer (ISR)   */


/* ===========================================================================
 *  ENCODER INITIALISATION
 * =========================================================================== */

/**
 * @brief  Start encoder counting for Motor A (TIM2) and Motor B (TIM3).
 *         Call this once after MX_TIMx_Init() in main().
 */
void Encoder_Init(void)
{
    /* ---- Motor A encoder: TIM2, CH1 (PA15) + CH2 (PB3) ---- */
    HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL);
    __HAL_TIM_SET_COUNTER(&htim2, 0);

    /* ---- Motor B encoder: TIM3, CH1 (PB4) + CH2 (PB5) ---- */
    HAL_TIM_Encoder_Start(&htim3, TIM_CHANNEL_ALL);
    __HAL_TIM_SET_COUNTER(&htim3, 0);

    /* Reset last count trackers */
    last_count_a = 0;
    last_count_b = 0;
}


/* ===========================================================================
 *  MOTOR PWM INITIALISATION
 * =========================================================================== */

/**
 * @brief  Start PWM outputs for Motor A (TIM4 CH3/CH4) and Motor B (TIM9 CH1/CH2).
 *         Call this once after MX_TIMx_Init() in main().
 */
void Motor_PWM_Init(void)
{
    /* ---- Motor A: TIM4 CH3 (PB8) + CH4 (PB9) ---- */
    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_3);
    HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_4);

    /* Start with motors stopped */
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, 0);
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, 0);

    /* ---- Motor B: TIM9 CH1 (PE5) + CH2 (PE6) ---- */
    HAL_TIM_PWM_Start(&htim9, TIM_CHANNEL_1);
    HAL_TIM_PWM_Start(&htim9, TIM_CHANNEL_2);

    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, 0);
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, 0);
}


/* ===========================================================================
 *  SAMPLING TIMER INITIALISATION
 * =========================================================================== */

/**
 * @brief  Start TIM6 as the periodic sampling timer for RPM calculation.
 *         TIM6 should be configured in CubeMX with:
 *           - Prescaler:  8399  (84 MHz / 8400 = 10 kHz tick)
 *           - Period:     99    (10 kHz / 100 = 100 Hz → 10 ms interval)
 *         Enable the TIM6 global interrupt in NVIC.
 */
void Encoder_Sampling_Timer_Init(void)
{
    HAL_TIM_Base_Start_IT(&htim6);
}


/* ===========================================================================
 *  MOTOR CONTROL FUNCTIONS
 * =========================================================================== */

/**
 * @brief  Drive Motor A forward at the given speed.
 * @param  speed  PWM duty cycle [0 .. MOTOR_PWM_MAX]
 */
void MotorA_Forward(uint16_t speed)
{
    if (speed > MOTOR_PWM_MAX) speed = MOTOR_PWM_MAX;
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, 0);   /* IN1 = 0 */
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, speed);       /* IN2 = PWM */
}

/**
 * @brief  Drive Motor A in reverse at the given speed.
 * @param  speed  PWM duty cycle [0 .. MOTOR_PWM_MAX]
 */
void MotorA_Reverse(uint16_t speed)
{
    if (speed > MOTOR_PWM_MAX) speed = MOTOR_PWM_MAX;
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, speed);       /* IN1 = PWM */
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, 0);   /* IN2 = 0 */
}

/**
 * @brief  Stop Motor A (coast).
 */
void MotorA_Stop(void)
{
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, 0);
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, 0);
}

/**
 * @brief  Brake Motor A (both outputs HIGH).
 */
void MotorA_Brake(void)
{
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_3, MOTOR_PWM_MAX);
    __HAL_TIM_SET_COMPARE(&htim4, TIM_CHANNEL_4, MOTOR_PWM_MAX);
}

/**
 * @brief  Drive Motor B forward at the given speed.
 * @param  speed  PWM duty cycle [0 .. MOTOR_PWM_MAX]
 */
void MotorB_Forward(uint16_t speed)
{
    if (speed > MOTOR_PWM_MAX) speed = MOTOR_PWM_MAX;
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, 0);   /* IN1 = 0 */
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, speed);       /* IN2 = PWM */
}

/**
 * @brief  Drive Motor B in reverse at the given speed.
 * @param  speed  PWM duty cycle [0 .. MOTOR_PWM_MAX]
 */
void MotorB_Reverse(uint16_t speed)
{
    if (speed > MOTOR_PWM_MAX) speed = MOTOR_PWM_MAX;
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, speed);       /* IN1 = PWM */
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, 0);   /* IN2 = 0 */
}

/**
 * @brief  Stop Motor B (coast).
 */
void MotorB_Stop(void)
{
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, 0);
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, 0);
}

/**
 * @brief  Brake Motor B (both outputs HIGH).
 */
void MotorB_Brake(void)
{
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_1, MOTOR_PWM_MAX);
    __HAL_TIM_SET_COMPARE(&htim9, TIM_CHANNEL_2, MOTOR_PWM_MAX);
}

/**
 * @brief  Set motor speed with signed value. Positive = forward, negative = reverse.
 * @param  motor   MOTOR_A or MOTOR_B
 * @param  speed   Signed speed [-MOTOR_PWM_MAX .. +MOTOR_PWM_MAX]
 */
void Motor_SetSpeed(Motor_ID_t motor, int16_t speed)
{
    uint16_t abs_speed = (speed >= 0) ? (uint16_t)speed : (uint16_t)(-speed);

    switch (motor)
    {
        case MOTOR_A:
            if (speed > 0)       MotorA_Forward(abs_speed);
            else if (speed < 0)  MotorA_Reverse(abs_speed);
            else                 MotorA_Stop();
            break;

        case MOTOR_B:
            if (speed > 0)       MotorB_Forward(abs_speed);
            else if (speed < 0)  MotorB_Reverse(abs_speed);
            else                 MotorB_Stop();
            break;

        default:
            break;
    }
}


/* ===========================================================================
 *  ENCODER READING & RPM CALCULATION
 * =========================================================================== */

/**
 * @brief  Read raw encoder count for a motor.
 * @param  motor  MOTOR_A or MOTOR_B
 * @return Signed 32-bit count (wraps around at 16-bit boundary for TIM3)
 */
int32_t Encoder_GetCount(Motor_ID_t motor)
{
    switch (motor)
    {
        case MOTOR_A:
            return (int32_t)__HAL_TIM_GET_COUNTER(&htim2);
        case MOTOR_B:
            return (int16_t)__HAL_TIM_GET_COUNTER(&htim3);  /* TIM3 is 16-bit */
        default:
            return 0;
    }
}

/**
 * @brief  Get the most recent RPM reading for a motor.
 * @param  motor  MOTOR_A or MOTOR_B
 * @return RPM as a float (positive = forward, negative = reverse)
 */
float Encoder_GetRPM(Motor_ID_t motor)
{
    switch (motor)
    {
        case MOTOR_A:  return rpm_motor_a;
        case MOTOR_B:  return rpm_motor_b;
        default:       return 0.0f;
    }
}

/**
 * @brief  Get the raw encoder delta (counts since last sample) for a motor.
 * @param  motor  MOTOR_A or MOTOR_B
 * @return Signed count delta
 */
int32_t Encoder_GetDelta(Motor_ID_t motor)
{
    switch (motor)
    {
        case MOTOR_A:  return encoder_delta_a;
        case MOTOR_B:  return encoder_delta_b;
        default:       return 0;
    }
}

/**
 * @brief  Reset encoder count to zero.
 * @param  motor  MOTOR_A or MOTOR_B
 */
void Encoder_Reset(Motor_ID_t motor)
{
    switch (motor)
    {
        case MOTOR_A:
            __HAL_TIM_SET_COUNTER(&htim2, 0);
            last_count_a = 0;
            break;
        case MOTOR_B:
            __HAL_TIM_SET_COUNTER(&htim3, 0);
            last_count_b = 0;
            break;
        default:
            break;
    }
}


/* ===========================================================================
 *  TIMER ISR CALLBACK  —  RPM CALCULATION
 * =========================================================================== */

/**
 * @brief  Called by HAL every time a timer period elapses.
 *         We hook TIM6 here to sample encoders and compute RPM.
 *
 *  RPM formula:
 *      delta       = current_count - last_count    (signed encoder ticks)
 *      revolutions = delta / COUNTS_PER_REV        (encoder ticks → shaft revolutions)
 *      RPM         = revolutions / sample_period_s * 60
 *
 *  With sample_period = 10 ms = 0.01 s:
 *      RPM = (delta / COUNTS_PER_REV) * (60 / 0.01)
 *      RPM = delta * 6000.0 / COUNTS_PER_REV
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
    if (htim->Instance == TIM6)
    {
        /* ---- Motor A (TIM2, 32-bit counter) ---- */
        int32_t current_a = (int32_t)__HAL_TIM_GET_COUNTER(&htim2);
        encoder_delta_a   = current_a - last_count_a;
        last_count_a      = current_a;

        rpm_motor_a = (float)encoder_delta_a * 6000.0f / (float)COUNTS_PER_REV;

        /* ---- Motor B (TIM3, 16-bit counter — must cast to int16_t for sign) ---- */
        int16_t raw_b     = (int16_t)__HAL_TIM_GET_COUNTER(&htim3);
        int16_t current_b = raw_b;
        encoder_delta_b   = (int32_t)-(current_b - (int16_t)last_count_b);
        last_count_b      = (int32_t)current_b;

        rpm_motor_b = (float)encoder_delta_b * 6000.0f / (float)COUNTS_PER_REV;
    }
}